<!DOCTYPE html>



  


<html class="theme-next muse use-motion" lang="">
<head><meta name="generator" content="Hexo 3.8.0">
  <meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta name="theme-color" content="#222">









<meta http-equiv="Cache-Control" content="no-transform">
<meta http-equiv="Cache-Control" content="no-siteapp">
















  
  
  <link href="/lib/fancybox/source/jquery.fancybox.css?v=2.1.5" rel="stylesheet" type="text/css">







<link href="/lib/font-awesome/css/font-awesome.min.css?v=4.6.2" rel="stylesheet" type="text/css">

<link href="/css/main.css?v=5.1.4" rel="stylesheet" type="text/css">


  <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon-next.png?v=5.1.4">


  <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32-next.png?v=5.1.4">


  <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16-next.png?v=5.1.4">


  <link rel="mask-icon" href="/images/logo.svg?v=5.1.4" color="#222">





  <meta name="keywords" content="Crash 分析,">










<meta name="description" content="什么是异常很多介绍操作系统的书在讲解“操作系统的运行机制”的时候都会提到“现代操作系统是靠中断驱动的软件”，这句话怎么理解？ 中断是指CPU对系统发生的某个事件做出的一种反应，CPU暂停正在执行的程序，保留现场后转去执行相应的处理程序，处理完该事件后再返回断点继续执行被“打断”的程序。 而引入中断技术的初衷是提高多道程序运行环境中CPU的利用率，比如CPU可以在I/O的执行过程中去执行其他指令，不">
<meta name="keywords" content="Crash 分析">
<meta property="og:type" content="article">
<meta property="og:title" content="CPU发生异常到生成Crash Log的过程">
<meta property="og:url" content="https://honchwong.github.io/2018/08/15/CPU发生异常到生成Crash Log的过程/index.html">
<meta property="og:site_name" content="honchwong">
<meta property="og:description" content="什么是异常很多介绍操作系统的书在讲解“操作系统的运行机制”的时候都会提到“现代操作系统是靠中断驱动的软件”，这句话怎么理解？ 中断是指CPU对系统发生的某个事件做出的一种反应，CPU暂停正在执行的程序，保留现场后转去执行相应的处理程序，处理完该事件后再返回断点继续执行被“打断”的程序。 而引入中断技术的初衷是提高多道程序运行环境中CPU的利用率，比如CPU可以在I/O的执行过程中去执行其他指令，不">
<meta property="og:locale" content="default">
<meta property="og:image" content="http://b303.photo.store.qq.com/psb?/V10JaO4w40EHz4/1OfXzk0RWT*5eExl0A5ilUXtBXPMYkyQBWwJwE5akK4!/b/dC8BAAAAAAAA&bo=VwY4BAAAAAADB08!&rf=viewer_4">
<meta property="og:updated_time" content="2019-02-10T12:21:16.552Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="CPU发生异常到生成Crash Log的过程">
<meta name="twitter:description" content="什么是异常很多介绍操作系统的书在讲解“操作系统的运行机制”的时候都会提到“现代操作系统是靠中断驱动的软件”，这句话怎么理解？ 中断是指CPU对系统发生的某个事件做出的一种反应，CPU暂停正在执行的程序，保留现场后转去执行相应的处理程序，处理完该事件后再返回断点继续执行被“打断”的程序。 而引入中断技术的初衷是提高多道程序运行环境中CPU的利用率，比如CPU可以在I/O的执行过程中去执行其他指令，不">
<meta name="twitter:image" content="http://b303.photo.store.qq.com/psb?/V10JaO4w40EHz4/1OfXzk0RWT*5eExl0A5ilUXtBXPMYkyQBWwJwE5akK4!/b/dC8BAAAAAAAA&bo=VwY4BAAAAAADB08!&rf=viewer_4">



<script type="text/javascript" id="hexo.configurations">
  var NexT = window.NexT || {};
  var CONFIG = {
    root: '/',
    scheme: 'Muse',
    version: '5.1.4',
    sidebar: {"position":"left","display":"post","offset":12,"b2t":false,"scrollpercent":false,"onmobile":false},
    fancybox: true,
    tabs: true,
    motion: {"enable":true,"async":false,"transition":{"post_block":"fadeIn","post_header":"slideDownIn","post_body":"slideDownIn","coll_header":"slideLeftIn","sidebar":"slideUpIn"}},
    duoshuo: {
      userId: '0',
      author: 'Author'
    },
    algolia: {
      applicationID: '',
      apiKey: '',
      indexName: '',
      hits: {"per_page":10},
      labels: {"input_placeholder":"Search for Posts","hits_empty":"We didn't find any results for the search: ${query}","hits_stats":"${hits} results found in ${time} ms"}
    }
  };
</script>



  <link rel="canonical" href="https://honchwong.github.io/2018/08/15/CPU发生异常到生成Crash Log的过程/">





  <title>CPU发生异常到生成Crash Log的过程 | honchwong</title>
  








</head>

<body itemscope="" itemtype="http://schema.org/WebPage" lang="default">

  
  
    
  

  <div class="container sidebar-position-left page-post-detail">
    <div class="headband"></div>

    <header id="header" class="header" itemscope="" itemtype="http://schema.org/WPHeader">
      <div class="header-inner"><div class="site-brand-wrapper">
  <div class="site-meta ">
    

    <div class="custom-logo-site-title">
      <a href="/" class="brand" rel="start">
        <span class="logo-line-before"><i></i></span>
        <span class="site-title">honchwong</span>
        <span class="logo-line-after"><i></i></span>
      </a>
    </div>
      
        <p class="site-subtitle"></p>
      
  </div>

  <div class="site-nav-toggle">
    <button>
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
    </button>
  </div>
</div>

<nav class="site-nav">
  

  
    <ul id="menu" class="menu">
      
        
        <li class="menu-item menu-item-home">
          <a href="/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-home"></i> <br>
            
            Home
          </a>
        </li>
      
        
        <li class="menu-item menu-item-archives">
          <a href="/archives/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-archive"></i> <br>
            
            Archives
          </a>
        </li>
      

      
    </ul>
  

  
</nav>



 </div>
    </header>

    <main id="main" class="main">
      <div class="main-inner">
        <div class="content-wrap">
          <div id="content" class="content">
            

  <div id="posts" class="posts-expand">
    

  

  
  
  

  <article class="post post-type-normal" itemscope="" itemtype="http://schema.org/Article">
  
  
  
  <div class="post-block">
    <link itemprop="mainEntityOfPage" href="https://honchwong.github.io/2018/08/15/CPU发生异常到生成Crash Log的过程/">

    <span hidden itemprop="author" itemscope="" itemtype="http://schema.org/Person">
      <meta itemprop="name" content="">
      <meta itemprop="description" content="">
      <meta itemprop="image" content="/images/avatar.gif">
    </span>

    <span hidden itemprop="publisher" itemscope="" itemtype="http://schema.org/Organization">
      <meta itemprop="name" content="honchwong">
    </span>

    
      <header class="post-header">

        
        
          <h1 class="post-title" itemprop="name headline">CPU发生异常到生成Crash Log的过程</h1>
        

        <div class="post-meta">
          <span class="post-time">
            
              <span class="post-meta-item-icon">
                <i class="fa fa-calendar-o"></i>
              </span>
              
                <span class="post-meta-item-text">Posted on</span>
              
              <time title="Post created" itemprop="dateCreated datePublished" datetime="2018-08-15T22:52:46+08:00">
                2018-08-15
              </time>
            

            

            
          </span>

          
            <span class="post-category">
            
              <span class="post-meta-divider">|</span>
            
              <span class="post-meta-item-icon">
                <i class="fa fa-folder-o"></i>
              </span>
              
                <span class="post-meta-item-text">In</span>
              
              
                <span itemprop="about" itemscope="" itemtype="http://schema.org/Thing">
                  <a href="/categories/Crash分析系列/" itemprop="url" rel="index">
                    <span itemprop="name">Crash分析系列</span>
                  </a>
                </span>

                
                
              
            </span>
          

          
            
          

          
          

          

          

          

        </div>
      </header>
    

    
    
    
    <div class="post-body" itemprop="articleBody">

      
      

      
        <h4 id="什么是异常"><a href="#什么是异常" class="headerlink" title="什么是异常"></a>什么是异常</h4><p>很多介绍操作系统的书在讲解<strong>“操作系统的运行机制”</strong>的时候都会提到<strong>“现代操作系统是靠中断驱动的软件”</strong>，这句话怎么理解？</p>
<p>中断是指CPU对系统发生的某个事件做出的一种反应，CPU暂停正在执行的程序，保留现场后转去执行相应的处理程序，处理完该事件后再返回断点继续执行被“打断”的程序。</p>
<p>而引入中断技术的初衷是提高多道程序运行环境中CPU的利用率，比如CPU可以在I/O的执行过程中去执行其他指令，不用空闲地去等待(或简单轮询) I/O设备的执行完成，I/O设备执行完成再通过中断通知CPU，以提高CPU利用率。后来中断技术逐步发展，成为操作系统各项操作的基础，比如进程调度，现代操作系统的进程调度一般都是采用基于时间片的优先级调度算法，把CPU的时间划分为很细粒度的时间片，执行一个任务的时间片用完了，时钟通过时钟中断去通知CPU切换任务，再比如下面要讨论到的CPU异常处理，也是基于中断机制去完成的。</p>
<p>中断(interrupt)和异常(exception)在不同的CPU架构里有不同的含义。</p>
<ul>
<li>比如在Intel架构中，中断处理的入口由操作系统内核中的中断分配表定义(interrupt dispatch table, IDT)，IDT中有255个中断向量，其中前20个定义为异常(exception)的处理入口，即中断包含异常。</li>
<li>而在ARM架构中，中断处理的入口则是在异常向量(exception vector)中，8个异常向量里边有3个是中断相关的，即异常包含中断。</li>
</ul>
<p>不管如何界定中断和异常，CPU发生异常时，都会将控制权从异常前的程序交给异常处理程序，而且CPU将获得 <strong><em>不会更低</em></strong> 的执行权利，比如执行用户态的应用程序发生异常，CPU将切换到内核态，并执行对应的异常处理程序。经典的CPU五级流水线中一条指令的生命周期为[取指、译码、执行、访存、写回]，每个阶段都可能出现CPU异常，比如在ARM架构下：</p>
<ul>
<li>在“执行”阶段产生的“数据中止”异常：若处理器 <strong><em>数据访问指令</em></strong> 的地址不存在，或该地址不允许当前指令访问时，产生数据中止异常。</li>
<li>在“取指”阶段产生的”预取中止“异常：若处理器 <strong><em>预取指令</em></strong> 的地址不存在，或该地址不允许当前指令访问，存储器会向处理器发出中止信号，但当预取的指令被执行时，才会产生指令预取中止异常。</li>
</ul>
<p>这两种异常对应的处理程序会直接或者间接调用 Mach 内核的 <code>exception_triage()</code> 函数，并将 <code>EXC_BAD_ACCESS</code> 作为入参传进去，<code>exception_triage()</code> 将会利用Mach消息传递机制投递异常。尽管Intel架构和ARM架构的CPU异常处理有些不同，但异常处理程序都会直接或间接将异常类型(<code>exception_type_t</code>)传给<code>exception_triage()</code>函数来处理异常，以此来屏蔽不同机器平台异常处理的差异。</p>
<p>异常类型(<code>exception_type_t</code>)在Mach层用int变量来存储，在<code>osfmk/mach/exception_types.h</code>文件中能看到Mach层定义的十几种异常，如常见的</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line">#define EXC_BAD_ACCESS      1   /* Could not access memory */</span><br><span class="line">        /* Code contains kern_return_t describing error. */</span><br><span class="line">        /* Subcode contains bad memory address. */</span><br><span class="line">#define EXC_CRASH           10  /* Abnormal process exit */</span><br><span class="line">#define EXC_CORPSE_NOTIFY   13  /* Abnormal process exited to corpse state */</span><br></pre></td></tr></table></figure>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line">int main(int argc, const char * argv[]) &#123;</span><br><span class="line">    int *pi = (int*)0x00001111;</span><br><span class="line">    *pi = 17;</span><br><span class="line">    return 0;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>上面这个程序中的非法内存访问将会用到上面列举三个异常类型，下面通过看源码、看书、代码调试来看下<code>exception_triage()</code> 函数都做了什么。</p>
<h4 id="调试跟踪CPU异常"><a href="#调试跟踪CPU异常" class="headerlink" title="调试跟踪CPU异常"></a>调试跟踪CPU异常</h4><p>在《深入解析Mac OS &amp; iOS 操作系统》中有讲解xnu异常处理的过程，但不是特别详细，而且书的参考代码与最新代码也有出入，要把内核的异常处理流程弄清楚，需要看书、看源码，当然少不了断点调试。</p>
<h5 id="调试xnu"><a href="#调试xnu" class="headerlink" title="调试xnu"></a>调试xnu</h5><p>在MacOS上调试XNU要比在iOS上调试简单，使用到的工具是：LLDB + VMware Fusion + Kernel Debug Kit ，调试环境的搭建只需简单几个步骤即可，可参考 <a href="http://www.cnblogs.com/elvirangel/p/9096517.html" target="_blank" rel="noopener">《MacOS内核调试环境搭建》</a> ，iOS上的调试可以参考lan beer 分享的 <a href="https://bugs.chromium.org/p/project-zero/issues/detail?id=1417#c16" target="_blank" rel="noopener">build your own iOS kernel debugger</a>，链接里有分享的PPT和PoC ，可惜目前的Poc仅支持iOS 11.1.2 </p>
<p>这里记录个在MacOS上调试XNU的坑，如果虚拟机到达“wait for the debugger” 阶段，并且在主机通过“kdp-remote” 连接虚拟机成功，但虚拟机继续启动的过程中一直卡在“Waiting for link to become available”，导致调试无法继续，就像<a href="https://forums.developer.apple.com/thread/35464" target="_blank" rel="noopener">这个帖子</a>中描述的问题一样</p>
<p>虽然我也没找到问题的具体原因，但摸出了个解决办法，就是在虚拟机启动时同时按下Option、Command、P 和 R，以reset NVRAM，将会进入到恢复模式，使用终端工具关闭虚拟机的SIP ，即输入命令csrutil disable，然后重启，启动后再走一遍 “内核替换”-&gt; “设置boot-args” -&gt; “清除kext缓存” -&gt; “重启虚拟机” -&gt; “主机连接虚拟机” 的流程，这时将会有百分之七十的概率能让虚拟机正常启动并可调试，如果不行就再试一次。</p>
<p>注：我使用的MacOs 版本是10.13.5，对应的XNU是4570.61.1，对应版本的源码没有放出，对比了前几个版本，我需要参考的源码都没有变动，所以参考源码是github上的<a href="https://github.com/apple/darwin-xnu/" target="_blank" rel="noopener">xnu-4570.1.46</a></p>
<h5 id="跟踪CPU异常"><a href="#跟踪CPU异常" class="headerlink" title="跟踪CPU异常"></a>跟踪CPU异常</h5><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">int main(int argc, const char * argv[]) &#123;</span><br><span class="line">    char c = getchar();</span><br><span class="line">    int *pi = (int*)0x00001111;</span><br><span class="line">    *pi = 17;</span><br><span class="line">    return 0;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>首先使用gcc来把上面这个程序编译成二进制可执行程序，然后运行。在程序等待键盘输入的时候，可以用ps命令查看进程PID是352。</p>
<p>在运行程序之前我在<code>osfmk/kern/exception.c</code> 的 <code>exception_triage_thread()</code> 函数实现处打了三个断点</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">breakpoint set --file exception.c --line 447</span><br><span class="line">breakpoint set --file exception.c --line 459</span><br><span class="line">breakpoint set --file exception.c --line 472</span><br></pre></td></tr></table></figure>
<p>447、459、472 分别是往 thread 层、task 层、host 层的异常端口数组投递异常，对应以下三行代码</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">（447）kr = exception_deliver(thread, exception, code, codeCnt, thread-&gt;exc_actions, mutex);</span><br><span class="line">（459）kr = exception_deliver(thread, exception, code, codeCnt, task-&gt;exc_actions, mutex);</span><br><span class="line">（472）kr = exception_deliver(thread, exception, code, codeCnt, host_priv-&gt;exc_actions, mutex);</span><br></pre></td></tr></table></figure>
<p>这三个断点只有一个断住了，那就是第472 行代码，到这里可以验证以下结论</p>
<p>首先通过lldb在终端输出函数调用栈、线程状态、进程PID</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line">(lldb) bt</span><br><span class="line">* thread #1, stop reason = breakpoint 4.1</span><br><span class="line">  * frame #0: 0xffffff800f97f0c9 kernel.development`exception_triage_thread(exception=1, code=0xffffff8014debf50, codeCnt=2, thread=0xffffff801c7c2a10) at exception.c:472 [opt]</span><br><span class="line">    frame #1: 0xffffff800fad71fb kernel.development`user_trap [inlined] exception_triage(code=0x0000000000000001) at exception.c:504 [opt]</span><br><span class="line">    frame #2: 0xffffff800fad71df kernel.development`user_trap [inlined] i386_exception(exc=1, code=&lt;unavailable&gt;) at trap.c:1152 [opt]</span><br><span class="line">    frame #3: 0xffffff800fad71d7 kernel.development`user_trap [inlined] user_page_fault_continue(kr=&lt;unavailable&gt;) at trap.c:232 [opt]</span><br><span class="line">    frame #4: 0xffffff800fad71d1 kernel.development`user_trap(saved_state=0xffffff8017246b20) at trap.c:1093 [opt]</span><br><span class="line">    frame #5: 0xffffff800f921102 kernel.development`hndl_alltraps + 226</span><br><span class="line">(lldb) e struct proc *$p_proc = (struct proc *)thread-&gt;task-&gt;bsd_info</span><br><span class="line">(lldb) po $p_proc-&gt;p_pid</span><br><span class="line">352</span><br><span class="line">(lldb) po thread-&gt;state</span><br><span class="line">4</span><br></pre></td></tr></table></figure>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">（注：线程状态用int变量存储，int state ，#define TH_SUSP 0x02 /*停止，或请求停止*/)</span><br></pre></td></tr></table></figure>
<p>以上log结合源码和《深入解析Mac OS &amp; iOS 操作系统》可以得出结论：</p>
<p>在Intel架构上，CPU执行用户态程序发生异常时会将对应进程挂起，并将CPU工作状态设置为内核态，还将执行XNU内核的异常处理程序。大多数操作系统都不会为每一个陷阱(异常)设置独立的处理程序，而是为所有的陷阱设置一个处理程序，然后这个处理程序通过<code>switch()</code>进行不同的处理，或者根据预定义的表跳转到不同的函数。XNU的做法也是如此，<code>hndl_alltraps</code>是公共陷阱处理程序，<code>user_trap</code>负责处理实际的陷阱，<code>hndl_alltraps</code>是用汇编语言写的，而<code>user_trap</code> 是用C语言写的，在<code>user_trap</code> 的实现里会调用<code>i386_exception</code>函数 ，<code>i386_exception</code>函数会调用<code>exception_triage</code>将陷阱转换为Mach 异常，在上面的程序中Mach 异常是 <code>EXC_BAD_ACCESS</code> 。</p>
<p><code>exception_triage()</code>函数的实现只有两行代码</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line">kern_return_t</span><br><span class="line">exception_triage(</span><br><span class="line">    exception_type_t    exception,</span><br><span class="line">    mach_exception_data_t   code,</span><br><span class="line">    mach_msg_type_number_t  codeCnt)</span><br><span class="line">&#123;</span><br><span class="line">    thread_t thread = current_thread();</span><br><span class="line">    return exception_triage_thread(exception, code, codeCnt, thread);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>第一行获取当前线程，这是因为第二行调用 <code>exception_triage_thread</code> 把异常投递到异常端口时需要用到current thread，thread、task的异常端口数组都需要通过 thread 获取到：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">thread-&gt;exc_actions;</span><br><span class="line">task = thread-&gt;task;</span><br><span class="line">task-&gt;exc_actions;</span><br><span class="line"></span><br><span class="line">host_priv = host_priv_self();</span><br><span class="line">host_priv-&gt;exc_actions;</span><br></pre></td></tr></table></figure>
<p>而thread、task的异常端口默认是NULL，host的异常端口是第一个用户态进程 launchd(PID 1)初始化的时候就设置好的了，而且内核初始化成功后所有的用户态进程都是launchd 的子进程，子进程通过父进程fork继承了父进程的异常端口，因此所有的用户态进程出现异常时，异常都能在host层得到统一处理。</p>
<p>launchd 进程是如何设置host的异常端口的？接受到异常消息如何处理？</p>
<p>内核初始化的过程中，第一个用户态进程launchd 是在<code>bsdinit_task()</code>函数里启动的，在启动launchd 进程前通过调用<code>host_set_exception_ports()</code> 函数，把所有的Mach 异常消息都定向到端口<code>ux_exception_port</code>，这个端口由一个内核线程持有，这个内核线程里执行的<code>ux_handle()</code>函数，这个函数里会在一个死循环里调用<code>mach_msg_receive()</code>来接受<code>ux_exception_port</code>端口上的消息，而且<code>mach_msg_receive()</code> 会阻塞线程。</p>
<p><code>ux_handle()</code>函数里接受到Mach消息后，会调用<code>mach_exc_server()</code>，而<code>mach_exc_server</code> 会调用下面的handlers ，具体调用哪个由参数 <code>exception_behavior_t behavior</code>决定，该参数是设置异常端口时调用<code>host_set_exception_ports()</code>传入的</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">catch_mach_exception_raise() 对应 EXCEPTION_DEFAULT  1  ，表示 xx</span><br><span class="line">catch_mach_exception_raise_state() 对应 define EXCEPTION_STATE  2 ，表示</span><br><span class="line">catch_mach_exception_raise_state_identity() 对应 define EXCEPTION_STATE_IDENTITY  3，表示</span><br></pre></td></tr></table></figure>
<p><code>catch_mach_exception_raise()</code>这些handle 会调用 <code>ux_exception()</code>将Mach异常转换成Unix信号，比如 <code>EXC_BAD_ACCESS</code>将会转换成 <code>SIGSEGV</code> 或 <code>SIGBUS</code> ，如代码所示</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line">static</span><br><span class="line">void ux_exception(</span><br><span class="line">        int         exception,</span><br><span class="line">        mach_exception_code_t   code,</span><br><span class="line">        mach_exception_subcode_t subcode,</span><br><span class="line">        int         *ux_signal,</span><br><span class="line">        mach_exception_code_t   *ux_code)</span><br><span class="line">&#123;</span><br><span class="line">    switch(exception) &#123;</span><br><span class="line"></span><br><span class="line">    case EXC_BAD_ACCESS:</span><br><span class="line">        if (code == KERN_INVALID_ADDRESS)</span><br><span class="line">            *ux_signal = SIGSEGV;</span><br><span class="line">        else</span><br><span class="line">            *ux_signal = SIGBUS;</span><br><span class="line">        break;</span><br><span class="line">    ....</span><br><span class="line">    &#125;</span><br><span class="line">    ....</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>在 <code>catch_mach_exception_raise()</code> 里拿到Mach异常对应的Unix信号后会再调用 <code>threadsignal()</code>投递Unix信号，在<code>threadsignal</code> 的实现里通过几层函数调用，最后会调用到<code>act_set_astbsd()</code> ，在该函数里设置了AST（异步软件中断）信号</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">void</span><br><span class="line">act_set_astbsd(</span><br><span class="line">    thread_t    thread)</span><br><span class="line">&#123;</span><br><span class="line">    act_set_ast( thread, AST_BSD );</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>AST 是人工引发的非硬件触发的陷阱，AST 是内核操作的关键部分，而且是调度事件的底层机制，也是BSD信号（Unix信号）投递的实现基础。当系统从一个陷阱返回时（<code>return_from_trap</code>），系统不会立即返回用户态，而是要检查线程的ast字段以判断是否存在AST 需要处理。如代码所示，此时AST的标志位是 <code>AST_BSD</code>，此标志位对应的handler 是<code>bsd_ast()</code> 函数。这时如果在<code>exception_triage()</code>下了断点，断点将会被断住，此时可以通过lldb在终端输出 函数调用栈、进程PID、线程状态</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line">(lldb) bt</span><br><span class="line">* thread #1, stop reason = breakpoint 1.17</span><br><span class="line">  * frame #0: 0xffffff800fe75fc9 kernel.development`proc_prepareexit [inlined] exception_triage(exception=10, code=0x000000000b100001, codeCnt=2) at exception.c:504 [opt]</span><br><span class="line">    frame #1: 0xffffff800fe75fbc kernel.development`proc_prepareexit [inlined] task_exception_notify(exception=10, exccode=185597953, excsubcode=4369) at exception.c:547 [opt]</span><br><span class="line">    frame #2: 0xffffff800fe75f96 kernel.development`proc_prepareexit(p=0xffffff8018d90b60, rv=&lt;unavailable&gt;, perf_notify=1) at kern_exit.c:889 [opt]</span><br><span class="line">    frame #3: 0xffffff800fe75d86 kernel.development`exit_with_reason(p=0xffffff8018d90b60, rv=11, retval=&lt;unavailable&gt;, thread_can_terminate=1, perf_notify=1, jetsam_flags=&lt;unavailable&gt;, exit_reason=&lt;unavailable&gt;) at kern_exit.c:830 [opt]</span><br><span class="line">    frame #4: 0xffffff800fe90675 kernel.development`postsig_locked(signum=11) at kern_sig.c:3140 [opt]</span><br><span class="line">    frame #5: 0xffffff800fe90b07 kernel.development`bsd_ast(thread=&lt;unavailable&gt;) at kern_sig.c:3420 [opt]</span><br><span class="line">    frame #6: 0xffffff800f973e44 kernel.development`ast_taken_user at ast.c:207 [opt]</span><br><span class="line">    frame #7: 0xffffff800f9211bc kernel.development`return_from_trap + 172</span><br><span class="line">(lldb) e struct proc *$proc_1 = (struct proc *)thread-&gt;task-&gt;bsd_info</span><br><span class="line">(lldb) po $proc_1-&gt;p_pid</span><br><span class="line">478</span><br><span class="line">(lldb) po thread-&gt;state</span><br><span class="line">4</span><br></pre></td></tr></table></figure>
<p>可以看到<code>bsd_ast()</code> 将会调用<code>postsig_locked()</code>数，从<code>/bsd/kern/kern_sig.c</code> <code>postsig_locked()</code>的实现可知，如果当前进程没有设置 sigaction 捕获Unix信号的话，默认处理是调用 <code>exit_with_reason()</code>，<code>exit_with_reason()</code>间接调用<code>task_exception_notify()</code>，<code>task_exception_notify()</code>的作用是通知launchd 去启动ReportCrash 生成CrashLog，通知的方式也是通过Mach消息传递机制，所以断点会在<code>exception_triage()</code>断住。</p>
<p>launchd 在初始化的过程中设置了异常端口，并且将 MachExceptionHandler 设置为<code>/System/Library/CoreServices/ReportCrash （iOS中的路径）</code>，ReportCrash将会生成Crash Log。前面说了 <code>exception_triage</code>调用 <code>exception_triage_thread()</code>投递异常，而<code>exception_triage_thread()</code>函数里执行异常投递的函数是<code>exception_deliver()</code>，查看上面log中的<code>frame #0</code>可以看到函数入参<code>exception=10 （EXC_CRASH）</code>，这是断点第二次在这断住，第一次断住是CPU异常转成Mach异常的时候，当时的<code>exception=1 (EXC_BAD_ACCESS)</code>，<code>exception_deliver()</code>函数将会利用入参 exception 从异常数组中取出具体的异常端口，所以第一次投递异常(CPU异常转Mach异常)和第二次投递异常给ReportCrash不会冲突。</p>
<p>此时再断点放掉，在 <code>exception_triage_thread()</code>处将会再出现一次断点</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line">(lldb) bt</span><br><span class="line">* thread #1, stop reason = breakpoint 2.1</span><br><span class="line">  * frame #0: 0xffffff800f97ef47 kernel.development`exception_triage_thread(exception=13, code=0xffffff806fce3e40, codeCnt=2, thread=0xffffff801cded250) at exception.c:445 [opt]</span><br><span class="line">    frame #1: 0xffffff800f9acffe kernel.development`task_deliver_crash_notification(task=0xffffff801d9af000, thread=0xffffff801cded250, etype=&lt;unavailable&gt;, subcode=&lt;unavailable&gt;) at task.c:1798 [opt]</span><br><span class="line">    frame #2: 0xffffff800f9b6537 kernel.development`thread_terminate_self at thread.c:594 [opt]</span><br><span class="line">    frame #3: 0xffffff800f9bab30 kernel.development`thread_apc_ast(thread=0xffffff801cded250) at thread_act.c:934 [opt]</span><br><span class="line">    frame #4: 0xffffff800f973e6b kernel.development`ast_taken_user at ast.c:220 [opt]</span><br><span class="line">    frame #5: 0xffffff800f9211bc kernel.development`return_from_trap + 172</span><br></pre></td></tr></table></figure>
<p>可以从函数调用栈看出，这也是设置AST 导致的，此时的<code>exception=13（EXC_CORPSE_NOTIFY）</code>，表示进程状态是僵尸状态，也就相当于死了。</p>
<p>通过打断点可以看出一个用户态应用程序非法访问内存导致的CPU异常，将会依次用到 <code>EXC_BAD_ACCESS、EXC_CRASH、EXC_CORPSE_NOTIFY</code>这三个Mach异常类型。</p>
<h5 id="小结"><a href="#小结" class="headerlink" title="小结"></a>小结</h5><p>(todo 换图片)<br>CPU异常 -&gt; Mach异常 -&gt; BSD层的Unix信号 -&gt; 用户态App Handler / 系统生成Crash Log 的流程可以简单粗略地画一个图</p>
<p><img src="http://b303.photo.store.qq.com/psb?/V10JaO4w40EHz4/1OfXzk0RWT*5eExl0A5ilUXtBXPMYkyQBWwJwE5akK4!/b/dC8BAAAAAAAA&amp;bo=VwY4BAAAAAADB08!&amp;rf=viewer_4" alt="s"></p>
<h4 id="异常收集"><a href="#异常收集" class="headerlink" title="异常收集"></a>异常收集</h4><p>虽然iOS \ macOS 都提供了 ReportCrash用来收集Crash 信息，Debug模式下也提供了 lldb 的debugserver 捕获程序异常，但App 发版上架后出现Crash 不方便开发者收集，比如在iOS上需要用户允许与开发者共享分析数据，开发者才可以从 iTunes Connect 查看到Crash 上报信息，不然则要拿到发生Crash的设备才能查看到Crash信息。</p>
<p>为了方便快速定位、解决Crash，可以借鉴 ReportCrash 或 debugserver 捕获异常的思路来做一个三方的Crash 收集的框架，收集思路主要有三种：</p>
<ul>
<li>捕获 Mach 异常</li>
<li>捕获 Unix 信号</li>
<li>NSSetUncaughtExceptionHandler</li>
</ul>
<h5 id="捕获Mach-异常"><a href="#捕获Mach-异常" class="headerlink" title="捕获Mach 异常"></a>捕获Mach 异常</h5><p>Mach 虽然非常底层，但也提供了API给用户态应用程序使用，捕获Mach异常可以使用以下几个API</p>
<ul>
<li>调用 mach_port_allocate 创建异常处理端口</li>
<li>调用 mach_port_insert_right 获取端口的权限</li>
<li>调用 xxx_set_exception_ports 设置异常端口</li>
<li>调用 mach_msg 等待异常端口上的消息</li>
</ul>
<p>这里有两个需要注意的点：</p>
<h5 id="捕获Unix-信号"><a href="#捕获Unix-信号" class="headerlink" title="捕获Unix 信号"></a>捕获Unix 信号</h5><h5 id="NSSetUncaughtExceptionHandler"><a href="#NSSetUncaughtExceptionHandler" class="headerlink" title="NSSetUncaughtExceptionHandler"></a>NSSetUncaughtExceptionHandler</h5><h5 id="埋点"><a href="#埋点" class="headerlink" title="埋点"></a>埋点</h5><p><a href="https://xiaozhuanlan.com/topic/6280793154" target="_blank" rel="noopener">https://xiaozhuanlan.com/topic/6280793154</a><br><a href="https://nianxi.net/ios/ios-crash-reporter.html" target="_blank" rel="noopener">https://nianxi.net/ios/ios-crash-reporter.html</a><br><a href="https://www.jianshu.com/p/80268ee99ddf" target="_blank" rel="noopener">https://www.jianshu.com/p/80268ee99ddf</a><br><a href="https://www.jianshu.com/p/34b98060965b" target="_blank" rel="noopener">https://www.jianshu.com/p/34b98060965b</a></p>
<h4 id="堆栈恢复-Crash-Log-格式"><a href="#堆栈恢复-Crash-Log-格式" class="headerlink" title="堆栈恢复 Crash Log 格式"></a>堆栈恢复 Crash Log 格式</h4>
      
    </div>
    
    
    

    

    

    

    <footer class="post-footer">
      
        <div class="post-tags">
          
            <a href="/tags/Crash-分析/" rel="tag"># Crash 分析</a>
          
        </div>
      

      
      
      

      
        <div class="post-nav">
          <div class="post-nav-next post-nav-item">
            
              <a href="/2018/05/05/Crash分析系列之一：LaunchDaemons中的ReportCrash/" rel="next" title="Crash分析系列之一：LaunchDaemons中的ReportCrash">
                <i class="fa fa-chevron-left"></i> Crash分析系列之一：LaunchDaemons中的ReportCrash
              </a>
            
          </div>

          <span class="post-nav-divider"></span>

          <div class="post-nav-prev post-nav-item">
            
              <a href="/2019/02/10/使用XLog、Spring-Boot、And-Design-Pro搭建日志系统/" rel="prev" title="使用XLog、Spring-Boot、And-Design-Pro搭建iOS日志系统">
                使用XLog、Spring-Boot、And-Design-Pro搭建iOS日志系统 <i class="fa fa-chevron-right"></i>
              </a>
            
          </div>
        </div>
      

      
      
    </footer>
  </div>
  
  
  
  </article>



    <div class="post-spread">
      
    </div>
  </div>


          </div>
          


          

  



        </div>
        
          
  
  <div class="sidebar-toggle">
    <div class="sidebar-toggle-line-wrap">
      <span class="sidebar-toggle-line sidebar-toggle-line-first"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-middle"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-last"></span>
    </div>
  </div>

  <aside id="sidebar" class="sidebar">
    
    <div class="sidebar-inner">

      

      
        <ul class="sidebar-nav motion-element">
          <li class="sidebar-nav-toc sidebar-nav-active" data-target="post-toc-wrap">
            Table of Contents
          </li>
          <li class="sidebar-nav-overview" data-target="site-overview-wrap">
            Overview
          </li>
        </ul>
      

      <section class="site-overview-wrap sidebar-panel">
        <div class="site-overview">
          <div class="site-author motion-element" itemprop="author" itemscope="" itemtype="http://schema.org/Person">
            
              <p class="site-author-name" itemprop="name"></p>
              <p class="site-description motion-element" itemprop="description"></p>
          </div>

          <nav class="site-state motion-element">

            
              <div class="site-state-item site-state-posts">
              
                <a href="/archives/">
              
                  <span class="site-state-item-count">6</span>
                  <span class="site-state-item-name">posts</span>
                </a>
              </div>
            

            
              
              
              <div class="site-state-item site-state-categories">
                <a href="/categories/index.html">
                  <span class="site-state-item-count">3</span>
                  <span class="site-state-item-name">categories</span>
                </a>
              </div>
            

            
              
              
              <div class="site-state-item site-state-tags">
                <a href="/tags/index.html">
                  <span class="site-state-item-count">5</span>
                  <span class="site-state-item-name">tags</span>
                </a>
              </div>
            

          </nav>

          

          

          
          

          
          

          

        </div>
      </section>

      
      <!--noindex-->
        <section class="post-toc-wrap motion-element sidebar-panel sidebar-panel-active">
          <div class="post-toc">

            
              
            

            
              <div class="post-toc-content"><ol class="nav"><li class="nav-item nav-level-4"><a class="nav-link" href="#什么是异常"><span class="nav-number">1.</span> <span class="nav-text">什么是异常</span></a></li><li class="nav-item nav-level-4"><a class="nav-link" href="#调试跟踪CPU异常"><span class="nav-number">2.</span> <span class="nav-text">调试跟踪CPU异常</span></a><ol class="nav-child"><li class="nav-item nav-level-5"><a class="nav-link" href="#调试xnu"><span class="nav-number">2.1.</span> <span class="nav-text">调试xnu</span></a></li><li class="nav-item nav-level-5"><a class="nav-link" href="#跟踪CPU异常"><span class="nav-number">2.2.</span> <span class="nav-text">跟踪CPU异常</span></a></li><li class="nav-item nav-level-5"><a class="nav-link" href="#小结"><span class="nav-number">2.3.</span> <span class="nav-text">小结</span></a></li></ol></li><li class="nav-item nav-level-4"><a class="nav-link" href="#异常收集"><span class="nav-number">3.</span> <span class="nav-text">异常收集</span></a><ol class="nav-child"><li class="nav-item nav-level-5"><a class="nav-link" href="#捕获Mach-异常"><span class="nav-number">3.1.</span> <span class="nav-text">捕获Mach 异常</span></a></li><li class="nav-item nav-level-5"><a class="nav-link" href="#捕获Unix-信号"><span class="nav-number">3.2.</span> <span class="nav-text">捕获Unix 信号</span></a></li><li class="nav-item nav-level-5"><a class="nav-link" href="#NSSetUncaughtExceptionHandler"><span class="nav-number">3.3.</span> <span class="nav-text">NSSetUncaughtExceptionHandler</span></a></li><li class="nav-item nav-level-5"><a class="nav-link" href="#埋点"><span class="nav-number">3.4.</span> <span class="nav-text">埋点</span></a></li></ol></li><li class="nav-item nav-level-4"><a class="nav-link" href="#堆栈恢复-Crash-Log-格式"><span class="nav-number">4.</span> <span class="nav-text">堆栈恢复 Crash Log 格式</span></a></li></ol></div>
            

          </div>
        </section>
      <!--/noindex-->
      

      

    </div>
  </aside>


        
      </div>
    </main>

    <footer id="footer" class="footer">
      <div class="footer-inner">
        <div class="copyright">&copy; <span itemprop="copyrightYear">2019</span>
  <span class="with-love">
    <i class="fa fa-user"></i>
  </span>
  <span class="author" itemprop="copyrightHolder"></span>

  
</div>


  <div class="powered-by">Powered by <a class="theme-link" target="_blank" href="https://hexo.io">Hexo</a></div>



  <span class="post-meta-divider">|</span>



  <div class="theme-info">Theme &mdash; <a class="theme-link" target="_blank" href="https://github.com/iissnan/hexo-theme-next">NexT.Muse</a> v5.1.4</div>




        







        
      </div>
    </footer>

    
      <div class="back-to-top">
        <i class="fa fa-arrow-up"></i>
        
      </div>
    

    

  </div>

  

<script type="text/javascript">
  if (Object.prototype.toString.call(window.Promise) !== '[object Function]') {
    window.Promise = null;
  }
</script>









  












  
  
    <script type="text/javascript" src="/lib/jquery/index.js?v=2.1.3"></script>
  

  
  
    <script type="text/javascript" src="/lib/fastclick/lib/fastclick.min.js?v=1.0.6"></script>
  

  
  
    <script type="text/javascript" src="/lib/jquery_lazyload/jquery.lazyload.js?v=1.9.7"></script>
  

  
  
    <script type="text/javascript" src="/lib/velocity/velocity.min.js?v=1.2.1"></script>
  

  
  
    <script type="text/javascript" src="/lib/velocity/velocity.ui.min.js?v=1.2.1"></script>
  

  
  
    <script type="text/javascript" src="/lib/fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>
  


  


  <script type="text/javascript" src="/js/src/utils.js?v=5.1.4"></script>

  <script type="text/javascript" src="/js/src/motion.js?v=5.1.4"></script>



  
  

  
  <script type="text/javascript" src="/js/src/scrollspy.js?v=5.1.4"></script>
<script type="text/javascript" src="/js/src/post-details.js?v=5.1.4"></script>



  


  <script type="text/javascript" src="/js/src/bootstrap.js?v=5.1.4"></script>



  


  




	





  





  












  





  

  

  

  
  

  

  

  

</body>
</html>
